<a href="https://colab.research.google.com/github/absolution-end/Learn_Neural_Networking/blob/main/basic_text.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import tensorflow as tf

sentences =["I love cats","i love dogs","I love Girls"]

In [28]:
# Initialize the layer
vectorize_layer = tf.keras.layers.TextVectorization()


In [29]:
# Build the vocabulary
vectorize_layer.adapt(sentences)

In [30]:
# Get the vocabulary list. Ignore special tokens for now.
vocabulary = vectorize_layer.get_vocabulary(include_special_tokens=False)

In [31]:
# Print the token index
for index, word in enumerate(vocabulary):
  print(index, word)

0 love
1 i
2 girls
3 dogs
4 cats


In [32]:
prompt_sent= 'Love is forever'
sent = vectorize_layer(prompt_sent)
print(sent)

tf.Tensor([2 1 1], shape=(3,), dtype=int64)


In [45]:
# Add another input
sentences = [
    'i love my dog',
    'I, love my cat',
    'You love my dog!',
    'How the fuck is you'
]

# Initialize the layer
vectorize_layer = tf.keras.layers.TextVectorization()

# Build the vocabulary
vectorize_layer.adapt(sentences)

# Get the vocabulary list. Ignore special tokens for now.
vocabulary = vectorize_layer.get_vocabulary(include_special_tokens=False)

In [46]:
# Print the token index
for index, word in enumerate(vocabulary):
  print(index, word)

0 my
1 love
2 you
3 i
4 dog
5 the
6 is
7 how
8 fuck
9 cat


In [47]:
# Get the vocabulary list.
vocabulary = vectorize_layer.get_vocabulary()

# Print the token index
for index, word in enumerate(vocabulary):
  print(index, word)

0 
1 [UNK]
2 my
3 love
4 you
5 i
6 dog
7 the
8 is
9 how
10 fuck
11 cat


In [55]:
# So here we are just taking input string and assigning it a number
# String input
sample_input = ['I love my dog','Good people build butiful girls']

# Convert the string input to an integer sequence
sequence = vectorize_layer(sample_input)

# Print the result
print(sequence)

tf.Tensor(
[[5 3 2 6 0]
 [1 1 1 1 1]], shape=(2, 5), dtype=int64)


In [64]:
# To assign a number we can use more efficinet thing which is to use #map()- function
# Convert the list to tf.data.Dataset
sentences_dataset = tf.data.Dataset.from_tensor_slices(sentences)

# Define a maping function to convert each sample input
sequences = sentences_dataset.map(vectorize_layer)

# print the integer sequence
for sentence, sequence in zip(sentences_dataset, sequence):
  print(f"{sentences} ----> {sequence}")

['i love my dog', 'I, love my cat', 'You love my dog!', 'How the fuck is you'] ----> 9
['i love my dog', 'I, love my cat', 'You love my dog!', 'How the fuck is you'] ----> 7
['i love my dog', 'I, love my cat', 'You love my dog!', 'How the fuck is you'] ----> 10
['i love my dog', 'I, love my cat', 'You love my dog!', 'How the fuck is you'] ----> 8


In [65]:
# Apply the layer to the string input list
sequences_post = vectorize_layer(sentences)

# Print the results
print('INPUT:')
print(sentences)
print()

print('OUTPUT:')
print(sequences_post)

INPUT:
['i love my dog', 'I, love my cat', 'You love my dog!', 'How the fuck is you']

OUTPUT:
tf.Tensor(
[[ 5  3  2  6  0]
 [ 5  3  2 11  0]
 [ 4  3  2  6  0]
 [ 9  7 10  8  4]], shape=(4, 5), dtype=int64)


In [73]:
# Here is the code for pre padding sequence to uniform length
sequence_pre = tf.keras.utils.pad_sequences(sequences, padding= 'pre')
print(sequence_pre)

[[ 0  5  3  2  6]
 [ 0  5  3  2 11]
 [ 0  4  3  2  6]
 [ 9  7 10  8  4]]


In [77]:
#  To pad the sequence and the limit the size we can use maxlen in the same function
sequences_post_trunc = tf.keras.utils.pad_sequences(sequences, maxlen=5, padding='pre')

# Print the results
print('INPUT:')
[print(sequence.numpy()) for sequence in sequences]
print()

print('OUTPUT:')
print(sequences_post_trunc)

INPUT:
[5 3 2 6]
[ 5  3  2 11]
[4 3 2 6]
[ 9  7 10  8  4]

OUTPUT:
[[ 0  5  3  2  6]
 [ 0  5  3  2 11]
 [ 0  4  3  2  6]
 [ 9  7 10  8  4]]


In [80]:
# another what to padd the sentences is to set the TextVector to ragged.
vectorization_layer = tf.keras.layers.TextVectorization(ragged=True)

vector_layer = vectorization_layer.adapt(sentences)

ragged_sentences = vectorization_layer(sentences)
print(ragged_sentences)

<tf.RaggedTensor [[5, 3, 2, 6], [5, 3, 2, 11], [4, 3, 2, 6], [9, 7, 10, 8, 4]]>


In [83]:
seq_pre = tf.keras.utils.pad_sequences(ragged_sentences.numpy(), maxlen=4)
print(seq_pre)

[[ 5  3  2  6]
 [ 5  3  2 11]
 [ 4  3  2  6]
 [ 7 10  8  4]]


In [84]:
# Try with words that are not in the vocabulary
sentences_with_oov = [
    'i really love my dog',
    'my dog loves my manatee'
]

# Generate the sequences
sequences_with_oov = vectorize_layer(sentences_with_oov)

# Print the integer sequences
for sentence, sequence in zip(sentences_with_oov, sequences_with_oov):
  print(f'{sentence} ---> {sequence}')

i really love my dog ---> [5 1 3 2 6]
my dog loves my manatee ---> [2 6 1 2 1]


In [86]:
!wget -nc https://storage.googleapis.com/tensorflow-1-public/course3/sarcasm.json

--2025-02-08 18:22:14--  https://storage.googleapis.com/tensorflow-1-public/course3/sarcasm.json
Resolving storage.googleapis.com (storage.googleapis.com)... 173.194.69.207, 173.194.79.207, 108.177.96.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|173.194.69.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5643545 (5.4M) [application/json]
Saving to: ‘sarcasm.json’

sarcasm.json        100%[===================>]   5.38M  7.16MB/s    in 0.8s    

2025-02-08 18:22:16 (7.16 MB/s) - ‘sarcasm.json’ saved [5643545/5643545]



In [91]:
import tensorflow as tf
import tensorflow_datasets as tfds
import json
from tensorflow.keras.utils import pad_sequences

In [93]:
# To load the json file
with open('/content/sarcasm.json','r') as f:
  datastore =json.load(f)

In [94]:
# Non-sarcastic headline
print(datastore[0])

# Sarcastic headline
print(datastore[20000])

{'article_link': 'https://www.huffingtonpost.com/entry/versace-black-code_us_5861fbefe4b0de3a08f600d5', 'headline': "former versace store clerk sues over secret 'black code' for minority shoppers", 'is_sarcastic': 0}
{'article_link': 'https://www.theonion.com/pediatricians-announce-2011-newborns-are-ugliest-babies-1819572977', 'headline': 'pediatricians announce 2011 newborns are ugliest babies in 30 years', 'is_sarcastic': 1}


In [104]:
sentences = list(item['headline'] for item in datastore)

In [108]:
vec_layer = tf.keras.layers.TextVectorization(ragged=True)
vec_layer.adapt(sentences)

post_padded_sequence = vec_layer(sentences)
print(post_padded_sequence)

<tf.RaggedTensor [[295, 15335, 801, 3788, 2264, 48, 362, 93, 2225, 6, 2578, 8719],
 [4, 8793, 3353, 2845, 28, 2, 156, 8515, 394, 2957, 6, 244, 9, 951],
 [140, 825, 2, 813, 1100, 2048, 571, 5057, 199, 139, 39, 46, 2, 13050],
 ..., [8862, 9, 66], [1832, 377, 3857, 5780, 866, 1665, 4618, 3546],
 [23100, 1692, 6, 4, 23598, 843]]>


In [112]:
# Print a sample headline and sequence
index = 2
print(f'sample headline: {sentences[index]}')
print(f'padded sequence: {post_padded_sequence[index]}')
print()

# Print dimensions of padded sequences
print(f'shape of padded sequences: {post_padded_sequence.shape}')

sample headline: mom starting to fear son's web series closest thing she will have to grandchild
padded sequence: [  140   825     2   813  1100  2048   571  5057   199   139    39    46
     2 13050]

shape of padded sequences: (26709, None)


In [113]:
ragged_sequences = vectorize_layer(sentences)

In [114]:
# Apply pre-padding to the ragged tensor
pre_padded_sequences = pad_sequences(ragged_sequences.numpy())

# Preview the result for the 2nd sequence
pre_padded_sequences[2]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [115]:
# Print a sample headline and sequence
index = 2
print(f'sample headline: {sentences[index]}')
print()
print(f'post-padded sequence: {post_padded_sequence[index]}')
print()
print(f'pre-padded sequence: {pre_padded_sequences[index]}')
print()

# Print dimensions of padded sequences
print(f'shape of post-padded sequences: {post_padded_sequence.shape}')
print(f'shape of pre-padded sequences: {pre_padded_sequences.shape}')


sample headline: mom starting to fear son's web series closest thing she will have to grandchild

post-padded sequence: [  140   825     2   813  1100  2048   571  5057   199   139    39    46
     2 13050]

pre-padded sequence: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]

shape of post-padded sequences: (26709, None)
shape of pre-padded sequences: (26709, 39)
